import{useEffect,useMemo,useState}from'react';
import{router}from'expo-router';
import{ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{BrandImage,GradientButton,Logo,Muted,OutlineButton,Panel,Screen,Title,COLORS}from'@/components/ui';
import{loadProducts,annualPriceFor}from'@/services/catalog';
import{read,write,KEY}from'@/services/storage';
import type{Product}from'@/services/types';

export default function Recommendation(){
  const[products,setProducts]=useState<Product[]>([]);const[selected,setSelected]=useState<string[]>([]);const[reasons,setReasons]=useState<Record<string,string[]>>({});const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  useEffect(()=>{(async()=>{try{const ids=(await read<string[]>(KEY.recommended,[])).slice(0,4);const reasonMap=await read<Record<string,string[]>>(KEY.recommendationMatches,{});const all=await loadProducts();const allowed=new Set(ids);const matched=all.filter(p=>allowed.has(p.id)&&p.active!==false&&p.productType!=='service'&&!/ai health (coach|advisor)/i.test(p.name));setProducts(matched);setReasons(reasonMap);const current=await read<string[]>(KEY.checkoutIds,[]);const valid=new Set(matched.map(p=>p.id));const next=current.filter(id=>valid.has(id));setSelected(next);await write(KEY.checkoutIds,next)}catch(e){setError(e instanceof Error?e.message:'Product catalogue could not be loaded.')}finally{setLoading(false)}})()},[]);
  async function toggle(id:string){const next=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id];setSelected(next);await write(KEY.checkoutIds,next)}
  const selectedProducts=useMemo(()=>{const ids=new Set(selected);return products.filter(p=>ids.has(p.id))},[products,selected]);
  const subtotal=selectedProducts.reduce((sum,p)=>sum+p.price,0);
  return <Screen><SafeAreaView style={{flex:1}}><View style={s.header}><Logo/><OutlineButton title="Log in" onPress={()=>router.push('/login')}/></View><ScrollView contentContainerStyle={s.body}><View style={{gap:8}}><Text style={s.kicker}>PRELIMINARY CATALOGUE MATCH</Text><Title size={30}>Choose from your preliminary recommendations</Title><Muted>Add only the products you want to take to checkout. Nothing is added automatically.</Muted></View><Panel style={s.notice}><Text style={s.noticeText}>Product details are shown from the active catalog. Medication and dosage remain reviewer-controlled.</Text></Panel>{error?<Panel><Text style={s.error}>{error}</Text></Panel>:null}{loading?<ActivityIndicator color={COLORS.teal}/>:<>{products.length===0?<Panel><Text style={s.cardTitle}>AI Health Coach only</Text><Muted>No active product matched the current goal/use-case tags. You can continue with advisor-only access.</Muted></Panel>:products.map(p=><Pressable key={p.id} onPress={()=>toggle(p.id)}><Panel style={[s.product,selected.includes(p.id)&&s.productOn]}><BrandImage uri={p.imageUrl} style={s.image}/><View style={{flex:1}}><View style={s.nameRow}><Text style={s.cardTitle}>{p.name}</Text><Text style={s.category}>{p.category}</Text></View><Muted style={{marginTop:3}}>{p.description||p.reason||p.category}</Muted>{(reasons[p.id]||[]).length?<Text style={s.reason}>Matched use cases: {(reasons[p.id]||[]).join(', ')}</Text>:null}<Text style={s.price}>${p.price.toFixed(2)}/month</Text><Text style={s.annual}>${(p.annualPrice??annualPriceFor(p.price)).toFixed(2)}/year · save 17%</Text></View><View style={[s.check,selected.includes(p.id)&&s.checkOn]}>{selected.includes(p.id)?<Text style={{color:'#0A1133',fontWeight:'900'}}>✓</Text>:null}</View></Panel></Pressable>)}<Panel style={{gap:8}}><Text style={s.cardTitle}>Selected for checkout</Text>{selectedProducts.length===0?<Muted>No products selected. Continue with AI Health Coach only, or add a recommended product above.</Muted>:selectedProducts.map(p=><View key={p.id} style={s.summaryRow}><Text style={s.summaryName}>{p.name}</Text><Text style={s.summaryPrice}>${p.price.toFixed(2)}</Text></View>)}{selectedProducts.length>0?<View style={s.total}><Text style={s.summaryName}>Product subtotal</Text><Text style={s.summaryPrice}>${subtotal.toFixed(2)}</Text></View>:null}<View style={s.advisor}><Text style={s.advisorText}>AI Health Coach: $19.99/month or $99/year. Choose the billing cycle on checkout.</Text></View><GradientButton title={selectedProducts.length?`Continue with ${selectedProducts.length} product${selectedProducts.length===1?'':'s'}`:'Continue with advisor only'} onPress={()=>router.push('/checkout')}/></Panel><OutlineButton title="Back to assessment" onPress={()=>router.replace('/assessment')}/></>}</ScrollView></SafeAreaView></Screen>
}
const s=StyleSheet.create({header:{height:64,paddingHorizontal:16,borderBottomWidth:1,borderBottomColor:COLORS.border,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},body:{padding:18,gap:14,paddingBottom:40},kicker:{color:COLORS.teal,fontSize:11,fontWeight:'800',letterSpacing:1.4},notice:{backgroundColor:'rgba(244,196,110,.07)'},noticeText:{color:'rgba(255,255,255,.78)',fontSize:12,lineHeight:18},product:{flexDirection:'row',gap:12,alignItems:'flex-start'},productOn:{borderColor:'rgba(122,199,200,.65)',backgroundColor:'rgba(122,199,200,.07)'},image:{width:82,height:82,borderRadius:12,backgroundColor:'#0E173D'},nameRow:{gap:5},cardTitle:{color:'#fff',fontSize:16,fontWeight:'800'},category:{alignSelf:'flex-start',color:'rgba(255,255,255,.6)',backgroundColor:'rgba(255,255,255,.07)',fontSize:9,fontWeight:'700',paddingHorizontal:7,paddingVertical:3,borderRadius:99,textTransform:'uppercase'},reason:{color:COLORS.teal,fontSize:11,marginTop:7},price:{color:'#fff',fontSize:14,fontWeight:'800',marginTop:8},annual:{color:'rgba(255,255,255,.55)',fontSize:11,marginTop:2},check:{width:25,height:25,borderRadius:8,borderWidth:1,borderColor:'rgba(255,255,255,.25)',alignItems:'center',justifyContent:'center'},checkOn:{backgroundColor:COLORS.teal,borderColor:COLORS.teal},summaryRow:{flexDirection:'row',justifyContent:'space-between',gap:10},summaryName:{color:'rgba(255,255,255,.75)',fontSize:12,flex:1},summaryPrice:{color:'#fff',fontSize:12,fontWeight:'800'},total:{borderTopWidth:1,borderTopColor:COLORS.border,paddingTop:10,marginTop:2,flexDirection:'row',justifyContent:'space-between'},advisor:{padding:10,borderRadius:10,backgroundColor:'rgba(255,255,255,.04)',borderWidth:1,borderColor:COLORS.border},advisorText:{color:'rgba(255,255,255,.62)',fontSize:11,lineHeight:16},error:{color:'#ffb0b8'}})
