import {useEffect,useMemo,useState} from 'react';
import {Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router} from 'expo-router';
import {Ionicons} from '@expo/vector-icons';
import {LinearGradient} from 'expo-linear-gradient';
import {DashboardHeader} from '@/components/DashboardHeader';
import {GradientButton,Muted,Panel,Screen,COLORS} from '@/components/ui';
import {useBranding} from '@/context/Branding';
import {loadDashboard,logNutrition,logWeight,submitCheckin,submitReviewerResponse,togglePlanProgress,type DashboardData,type ProgressItem} from '@/services/member';

export default function Dashboard(){
 const b=useBranding(); const[data,setData]=useState<DashboardData|null>(null);const[err,setErr]=useState('');const[refreshing,setRefreshing]=useState(false);const[busy,setBusy]=useState('');const[weight,setWeight]=useState('');const[review,setReview]=useState('');const[nutrition,setNutrition]=useState({protein:'',carbs:'',water:''});const[checkin,setCheckin]=useState({energy:'',adherence:'',sleep:'',note:''});
 const load=async()=>{try{setErr('');setData(await loadDashboard())}catch(e){setErr(e instanceof Error?e.message:'Dashboard could not be loaded.')}};
 useEffect(()=>{void load()},[]);
 const pct=useMemo(()=>{if(!data)return 0;const t=data.progress.weeklyTotal+data.progress.workoutTotal+1,d=data.progress.weeklyCompleted+data.progress.workoutCompleted+(data.progress.checkinThisWeek?1:0);return t?Math.round(d/t*100):0},[data]);
 const act=async(key:string,fn:()=>Promise<any>,done?:string)=>{setBusy(key);try{const value=await fn();if(value?.weeklyTargets)setData(c=>c?{...c,progress:value}:c);if(done)Alert.alert('Saved',done)}catch(e){Alert.alert('Could not save',e instanceof Error?e.message:'Please try again.')}finally{setBusy('')}};
 const toggle=async(type:'weekly_target'|'workout',item:ProgressItem)=>act(`${type}:${item.key}`,()=>togglePlanProgress(type,item.item,!item.completed));
 if(!data&&!err)return <Screen><SafeAreaView style={s.fill}><DashboardHeader title="Dashboard" sub="Loading your account…"/><View style={s.center}><Text style={s.muted}>Loading dashboard…</Text></View></SafeAreaView></Screen>;
 return <Screen><SafeAreaView style={s.fill} edges={['top']}><DashboardHeader title="Dashboard" sub={b.dashboardDescription||'Your plan, progress and purchases in one place.'}/><ScrollView refreshControl={<RefreshControl refreshing={refreshing} tintColor={COLORS.teal} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}/>} contentContainerStyle={s.body} keyboardShouldPersistTaps="handled">
 {err?<Panel><Text style={s.error}>{err}</Text><View style={{marginTop:12}}><GradientButton title="Try again" onPress={load}/></View></Panel>:data?<>
 <View style={s.hello}><View style={{flex:1}}><Text style={s.eyebrow}>{b.dashboardTitle}</Text><Text style={s.h1}>Hello, {data.user.firstName}.</Text><Muted>{data.plan?.focus||'Your reviewed plan and recommendations will appear here.'}</Muted></View><LinearGradient colors={[b.primaryColor,b.gradientMidColor,b.secondaryColor,b.accentColor] as any} style={s.orb}><Ionicons name="sparkles" size={25} color="#fff"/></LinearGradient></View>
 <View style={s.metrics}><Metric icon="heart-outline" label="Goal" value={data.plan?.goal||'Pending plan creation'}/><Metric icon="medkit-outline" label="Medication" value={data.plan?.medication||'Reviewer pending'}/><Metric icon="shield-checkmark-outline" label="Dosage" value={data.plan?.dosage||'Reviewer pending'}/></View>
 <Panel><View style={s.row}><View><Text style={s.cardTitle}>Weekly progress</Text><Text style={s.percent}>{data.plan?.status==='released'?`${pct}%`:'—'}</Text></View><Pressable onPress={()=>router.push('/dashboard/plan')}><Text style={s.link}>Plan details ›</Text></Pressable></View><View style={s.track}><LinearGradient colors={[b.primaryColor,b.gradientMidColor,b.secondaryColor] as any} style={{height:8,borderRadius:99,width:`${pct}%` as any}}/></View><Muted>{data.progress.weeklyCompleted}/{data.progress.weeklyTotal} targets · {data.progress.workoutCompleted}/{data.progress.workoutTotal} workouts</Muted></Panel>
 {data.plan?.status==='needs_information'?<Panel style={s.warning}><Text style={s.warningTitle}>Your reviewer needs more information</Text><Muted>{data.plan.requestedInformation}</Muted><TextInput multiline value={review} onChangeText={setReview} placeholder="Reply to your reviewer…" placeholderTextColor="rgba(255,255,255,.35)" style={s.textarea}/><GradientButton title={busy==='review'?'Sending…':'Send to reviewer'} disabled={!review.trim()||busy==='review'} onPress={()=>act('review',async()=>{const plan=await submitReviewerResponse(review.trim());setData(c=>c?{...c,plan}:c);setReview('')},'Response sent to your reviewer.')}/></Panel>:null}
 {data.plan?.status==='released'?<>
 <Panel><Text style={s.cardTitle}>This week</Text><Muted style={{marginBottom:12}}>Your reviewer controls these targets. Completion resets each Monday.</Muted><Track title="Weekly targets" type="weekly_target" items={data.progress.weeklyTargets||[]} busy={busy} toggle={toggle}/><Track title="Workouts" type="workout" items={data.progress.workouts||[]} busy={busy} toggle={toggle}/></Panel>
 <Panel><Text style={s.cardTitle}>Weight</Text><View style={s.formRow}><TextInput value={weight} onChangeText={setWeight} keyboardType="decimal-pad" placeholder="Weight in lb" placeholderTextColor="rgba(255,255,255,.35)" style={s.smallInput}/><Pressable onPress={()=>{const n=Number(weight);if(!Number.isFinite(n)||n<50||n>1000)return Alert.alert('Invalid weight','Enter a value between 50 and 1000 lb.');void act('weight',()=>logWeight(n),'Weight logged.').then(()=>setWeight(''))}}><Text style={s.action}>Log weight</Text></Pressable></View>{data.progress.latestWeight?<Muted>Latest: {data.progress.latestWeight.weightLbs} lb</Muted>:null}</Panel>
 <Panel><Text style={s.cardTitle}>Weekly check-in</Text><View style={s.three}><MiniInput label="Energy 1–10" value={checkin.energy} set={v=>setCheckin(c=>({...c,energy:v}))}/><MiniInput label="Adherence %" value={checkin.adherence} set={v=>setCheckin(c=>({...c,adherence:v}))}/><MiniInput label="Sleep hrs" value={checkin.sleep} set={v=>setCheckin(c=>({...c,sleep:v}))}/></View><TextInput multiline value={checkin.note} onChangeText={v=>setCheckin(c=>({...c,note:v}))} placeholder="Anything your reviewer should know?" placeholderTextColor="rgba(255,255,255,.35)" style={s.textarea}/><GradientButton title={busy==='checkin'?'Saving…':'Save check-in'} disabled={busy==='checkin'} onPress={()=>act('checkin',()=>submitCheckin({energyScore:checkin.energy?Number(checkin.energy):undefined,adherenceScore:checkin.adherence?Number(checkin.adherence):undefined,sleepHours:checkin.sleep?Number(checkin.sleep):undefined,note:checkin.note.trim()||undefined}),'Check-in saved.').then(()=>setCheckin({energy:'',adherence:'',sleep:'',note:''}))}/></Panel>
 <Panel><Text style={s.cardTitle}>Nutrition today</Text><View style={s.three}><MiniInput label="Protein g" value={nutrition.protein} set={v=>setNutrition(c=>({...c,protein:v}))}/><MiniInput label="Carbs g" value={nutrition.carbs} set={v=>setNutrition(c=>({...c,carbs:v}))}/><MiniInput label="Water oz" value={nutrition.water} set={v=>setNutrition(c=>({...c,water:v}))}/></View><GradientButton title={busy==='nutrition'?'Saving…':'Save nutrition'} disabled={busy==='nutrition'} onPress={()=>act('nutrition',()=>logNutrition({proteinGrams:Number(nutrition.protein||0),carbsGrams:Number(nutrition.carbs||0),hydrationOz:Number(nutrition.water||0)}),'Nutrition saved.').then(()=>setNutrition({protein:'',carbs:'',water:''}))}/></Panel>
 </>:null}
 <Pressable onPress={()=>router.push('/dashboard/coach')}><LinearGradient colors={[b.primaryColor,b.gradientMidColor,b.secondaryColor,b.accentColor] as any} style={s.coach}><View style={s.coachIcon}><Ionicons name="chatbubble-ellipses-outline" size={22} color="#fff"/></View><View style={{flex:1}}><Text style={s.coachTitle}>AI Health Coach</Text><Text style={s.coachSub}>Private coach personalized to your account</Text></View><Ionicons name="chevron-forward" color="#fff" size={20}/></LinearGradient></Pressable>
 </>:null}
 </ScrollView></SafeAreaView></Screen>
}
function Metric({icon,label,value}:{icon:any;label:string;value:string}){return <Panel style={s.metric}><Ionicons name={icon} size={18} color={COLORS.teal}/><Text style={s.metricLabel}>{label}</Text><Text numberOfLines={3} style={s.metricValue}>{value}</Text></Panel>}
function Track({title,type,items,busy,toggle}:{title:string;type:'weekly_target'|'workout';items:ProgressItem[];busy:string;toggle:(t:'weekly_target'|'workout',i:ProgressItem)=>void}){return <View style={{gap:8,marginTop:10}}><Text style={s.subhead}>{title}</Text>{items.length?items.map(i=><Pressable key={i.key} disabled={busy===`${type}:${i.key}`} onPress={()=>toggle(type,i)} style={s.trackItem}><Ionicons name={i.completed?'checkmark-circle':'ellipse-outline'} size={21} color={i.completed?COLORS.green:'rgba(255,255,255,.45)'}/><Text style={[s.trackText,i.completed&&{opacity:.55,textDecorationLine:'line-through'}]}>{i.item}</Text></Pressable>):<Muted>No targets published yet.</Muted>}</View>}
function MiniInput({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <View style={{flex:1,gap:5}}><Text style={s.miniLabel}>{label}</Text><TextInput keyboardType="decimal-pad" value={value} onChangeText={set} style={s.miniInput}/></View>}
const s=StyleSheet.create({fill:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center'},body:{padding:16,gap:12,paddingBottom:100},muted:{color:'rgba(255,255,255,.55)'},error:{color:'#fecaca',fontSize:13,lineHeight:20},hello:{flexDirection:'row',gap:14,alignItems:'center',paddingVertical:5},eyebrow:{color:'rgba(255,255,255,.55)',fontSize:12},h1:{color:'#fff',fontSize:29,fontWeight:'900',marginVertical:4},orb:{width:64,height:64,borderRadius:22,alignItems:'center',justifyContent:'center'},metrics:{gap:10},metric:{gap:5,padding:14},metricLabel:{color:'rgba(255,255,255,.5)',fontSize:10,textTransform:'uppercase',letterSpacing:1.1,fontWeight:'800'},metricValue:{color:'#fff',fontWeight:'800',fontSize:14},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},cardTitle:{color:'#fff',fontSize:17,fontWeight:'800',marginBottom:5},percent:{color:'#fff',fontSize:30,fontWeight:'900'},link:{color:'#fff',fontSize:12,fontWeight:'700'},track:{height:8,backgroundColor:'rgba(255,255,255,.08)',borderRadius:99,overflow:'hidden',marginVertical:10},warning:{borderColor:'rgba(244,196,110,.35)',backgroundColor:'rgba(244,196,110,.08)'},warningTitle:{color:COLORS.warning,fontSize:15,fontWeight:'800',marginBottom:5},textarea:{minHeight:92,borderWidth:1,borderColor:'rgba(255,255,255,.14)',borderRadius:12,color:'#fff',padding:12,textAlignVertical:'top',fontSize:13,marginVertical:10},subhead:{color:'#fff',fontWeight:'700',fontSize:13},trackItem:{minHeight:42,flexDirection:'row',alignItems:'center',gap:9,borderBottomWidth:1,borderBottomColor:'rgba(255,255,255,.06)'},trackText:{color:'rgba(255,255,255,.85)',fontSize:13,flex:1},formRow:{flexDirection:'row',gap:8,alignItems:'center',marginVertical:8},smallInput:{flex:1,height:44,borderWidth:1,borderColor:'rgba(255,255,255,.14)',borderRadius:10,color:'#fff',paddingHorizontal:12},action:{color:'#fff',fontWeight:'800',fontSize:12,padding:12},three:{flexDirection:'row',gap:8,marginVertical:8},miniLabel:{color:'rgba(255,255,255,.5)',fontSize:9.5},miniInput:{height:42,borderWidth:1,borderColor:'rgba(255,255,255,.14)',borderRadius:9,color:'#fff',paddingHorizontal:9},coach:{minHeight:82,borderRadius:18,padding:14,flexDirection:'row',alignItems:'center',gap:12},coachIcon:{width:44,height:44,borderRadius:14,backgroundColor:'rgba(255,255,255,.12)',alignItems:'center',justifyContent:'center'},coachTitle:{color:'#fff',fontWeight:'900',fontSize:15},coachSub:{color:'rgba(255,255,255,.65)',fontSize:11,marginTop:2}})
