import{useEffect,useMemo,useState}from'react';
import{router}from'expo-router';
import{ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{DashboardHeader}from'@/components/DashboardHeader';
import{BrandImage,GradientButton,Muted,Panel,Screen,COLORS}from'@/components/ui';
import{loadDashboard,loadProductSubscriptions}from'@/services/member';
import{loadProducts,annualPriceFor}from'@/services/catalog';
import{write,KEY}from'@/services/storage';
import type{Product}from'@/services/types';

export default function Recommendation(){
  const[data,setData]=useState<any>(null);const[catalog,setCatalog]=useState<Product[]>([]);const[purchased,setPurchased]=useState<Set<string>>(new Set());const[error,setError]=useState('');
  useEffect(()=>{Promise.all([loadDashboard(),loadProducts(),loadProductSubscriptions()]).then(([d,p,subs])=>{setData(d);setCatalog(p.filter(x=>x.active!==false&&x.productType!=='service'&&!/ai health (coach|advisor)/i.test(x.name)));setPurchased(new Set([...(d.order?.selectedProductIds||[]),...subs.filter((s:any)=>s.status==='active'||s.status==='cancel_at_period_end').map((s:any)=>s.productId)]))}).catch(e=>setError(e instanceof Error?e.message:'Recommendation could not be loaded.'))},[]);
  const selected=useMemo(()=>catalog.filter(p=>purchased.has(p.id)),[catalog,purchased]);
  const more=useMemo(()=>{if(!data?.plan)return[];const planIds=new Set<string>(data.plan.productIds||[]);const context=`${data.plan.goal||data.plan.primaryGoal||''} ${(data.plan.categories||[]).join(' ')} ${data.plan.focus||''}`.toLowerCase();return catalog.filter(p=>!purchased.has(p.id)).map(p=>{const terms=[...(p.goalTags||[]),...(p.tags||[]),...(p.useCases||[])].map(x=>x.trim().toLowerCase()).filter(Boolean);const score=terms.reduce((n,t)=>n+(context.includes(t)?2:0),0);return{p,score,original:planIds.has(p.id)}}).filter(x=>x.original||x.score>0).sort((a,b)=>Number(b.original)-Number(a.original)||b.score-a.score||(a.p.sortOrder??999)-(b.p.sortOrder??999)).slice(0,6).map(x=>x.p)},[catalog,data,purchased]);
  async function order(p:Product){await write(KEY.checkoutIds,[p.id]);router.push('/checkout')}
  if(error)return <Screen><SafeAreaView style={{flex:1}}><DashboardHeader title="Recommendation"/><View style={s.body}><Panel><Text style={s.error}>{error}</Text></Panel></View></SafeAreaView></Screen>;
  if(!data)return <Screen><SafeAreaView style={{flex:1}}><DashboardHeader title="Recommendation"/><View style={s.loading}><ActivityIndicator color={COLORS.teal}/></View></SafeAreaView></Screen>;
  const plan=data.plan;if(!plan)return <Screen><SafeAreaView style={{flex:1}}><DashboardHeader title="Recommendation"/><View style={s.body}><Panel><Text style={s.name}>No recommendation yet</Text><Muted style={{marginTop:6}}>Complete checkout and account creation first.</Muted></Panel></View></SafeAreaView></Screen>;
  const released=plan.status==='released';
  if(!released)return <Screen><SafeAreaView style={{flex:1}}><DashboardHeader title="Recommendation"/><View style={s.body}><Panel><Text style={s.badge}>{String(plan.status||'needs_review').replaceAll('_',' ')}</Text><Text style={[s.name,{fontSize:20,marginTop:10}]}>Your plan is being reviewed</Text><Muted style={{marginTop:6}}>A reviewer must publish the reviewed plan before reviewer-controlled details are shown here.</Muted></Panel></View></SafeAreaView></Screen>;
  return <Screen><SafeAreaView style={{flex:1}}><DashboardHeader title="Recommendation" sub="Products connected to your released plan."/><ScrollView contentContainerStyle={s.body}><Panel style={{gap:7}}><Text style={s.eyebrow}>PRIMARY GOAL</Text><Text style={s.name}>{plan.goal||plan.primaryGoal||'Wellness plan'}</Text><Muted>{plan.focus||''}</Muted></Panel>{selected.length>0?<View style={{gap:10}}><Text style={s.section}>Your products</Text>{selected.map(p=><ProductCard key={p.id} p={p} purchased/>)}</View>:null}<View style={{gap:10}}><Text style={s.section}>More products for your goals</Text><Muted>Only products matched to your assessment or released plan are shown. Products you already purchased are removed.</Muted>{more.map(p=><ProductCard key={p.id} p={p} onOrder={()=>order(p)}/>)}{more.length===0?<Panel><Muted>You currently have all active products relevant to this catalog.</Muted></Panel>:null}</View></ScrollView></SafeAreaView></Screen>
}
function ProductCard({p,purchased,onOrder}:{p:Product;purchased?:boolean;onOrder?:()=>void}){return <Panel style={s.row}><BrandImage uri={p.imageUrl} style={s.img}/><View style={{flex:1,gap:4}}><Text style={s.name}>{p.name}</Text><Muted>{p.description||p.category}</Muted><Text style={s.price}>${p.price.toFixed(2)}/mo</Text><Text style={s.annual}>${(p.annualPrice??annualPriceFor(p.price)).toFixed(2)}/yr · save 17%</Text>{purchased?<Text style={s.purchased}>Purchased</Text>:<View style={{marginTop:6}}><GradientButton title="Order" onPress={onOrder}/></View>}</View></Panel>}
const s=StyleSheet.create({body:{padding:18,gap:16,paddingBottom:36},loading:{flex:1,alignItems:'center',justifyContent:'center'},row:{flexDirection:'row',gap:12,alignItems:'flex-start'},img:{width:86,height:86,borderRadius:12},name:{color:'#fff',fontWeight:'900',fontSize:15},price:{color:'#fff',fontWeight:'800',marginTop:5},annual:{color:'rgba(255,255,255,.5)',fontSize:11},section:{color:'#fff',fontSize:16,fontWeight:'900'},eyebrow:{fontSize:10,color:COLORS.teal,fontWeight:'900',letterSpacing:1.3},badge:{alignSelf:'flex-start',color:'#F4C46E',backgroundColor:'rgba(244,196,110,.12)',paddingHorizontal:10,paddingVertical:5,borderRadius:99,fontSize:10,fontWeight:'800',textTransform:'uppercase'},purchased:{alignSelf:'flex-start',marginTop:6,color:'#B9F5D8',backgroundColor:'rgba(112,214,178,.10)',paddingHorizontal:10,paddingVertical:6,borderRadius:99,fontSize:11,fontWeight:'800'},error:{color:'#ffb0b8'}})
